### PR TITLE
fix inconsistent chords between dot io and default library

### LINKED ISSUE #26: Different CC1 chords between Dot I/O and default chord library
I took the chord list from both Dot I/O program and default chord library of CC1 and found differences (listed in the json below).
I can submit PR for the mismatch and wrong parts (such as `began`, `its`) but should I remove ones that doesn't exist in default chord library (such as `as`)?

```json
[
  {
    "word": "will",
    "dotIOChord": "i + l + w",
    "libraryChords": [
      "i + l + w + DUP"
    ]
  },
  {
    "word": "your",
    "dotIOChord": "r + y",
    "libraryChords": [
      "o + r + u + y"
    ]
  },
  {
    "word": "also",
    "dotIOChord": "a + l + o",
    "libraryChords": [
      "a + l + o + s"
    ]
  },
  {
    "word": "as",
    "dotIOChord": "a + s",
    "libraryChords": null
  },
  {
    "word": "began",
    "dotIOChord": "b + g + present tense",
    "libraryChords": [
      "a + b + e + g + n"
    ]
  },
  {
    "word": "every",
    "dotIOChord": "e + v + y",
    "libraryChords": [
      "e + v + y + DUP",
      "e + r + v + y + DUP"
    ]
  },
  {
    "word": "had",
    "dotIOChord": "a + h",
    "libraryChords": [
      "a + d + h"
    ]
  },
  {
    "word": "its",
    "dotIOChord": "i + t + past tense + plural",
    "libraryChords": null
  },
  {
    "word": "last",
    "dotIOChord": "a + l + t",
    "libraryChords": [
      "a + l + s",
      "a + l + s + t",
      "a + l + u"
    ]
  },
  {
    "word": "near",
    "dotIOChord": "n + r",
    "libraryChords": [
      "a + e + n + r"
    ]
  },
  {
    "word": "quick",
    "dotIOChord": "i + k + q + u",
    "libraryChords": [
      "k + q",
      "c + i + k + q",
      "k + q + u",
      "c + i + k + q + u"
    ]
  },
  {
    "word": "quite",
    "dotIOChord": "e + q + t + u",
    "libraryChords": [
      "e + i + q + t",
      "e + i + q + t + u"
    ]
  },
  {
    "word": "saw",
    "dotIOChord": "s + w",
    "libraryChords": [
      "a + s",
      "a + s + w"
    ]
  },
  {
    "word": "three",
    "dotIOChord": "e + h + r + t",
    "libraryChords": [
      "  + 3",
      "e + h + r + t + DUP"
    ]
  },
  {
    "word": "watch",
    "dotIOChord": "h + t + w",
    "libraryChords": [
      "a + t + w",
      "a + h + t + w"
    ]
  }
]
```

### PR DESCRIPTION
**Pull request by andy23512**
Fix #26
- will -> i + l + w + DUP
- your -> o + r + u + y
- also -> a + l + o + s
- as -> (removed)
- began -> b + g + past tense
- every -> e + v + y + DUP
- had -> a + d + h
- its -> i + t + plural
- last -> a + l + s
- near -> a + e + n + r
- quick -> k + q
- quite -> e + i + q + t
- saw -> a + s
- three -> e + h + r + t + DUP
- watch -> a + t + w

### CODE REVIEW

**Comment by jdestgermain** [comment]
Whenever I was looking into doing this, I was stumped by what these numbers are representing. Could you explain what they are so it is easier to review this PR?

https://github.com/iq-eq-us/dot-io/discussions/25

**Comment by andy23512** [comment]
The numbers seems to be some positions on device. I collect the mapping mainly from https://github.com/iq-eq-us/dot-io/blob/latest_branch/src/data/chordLibrary.ts#L377-L404 .
```
const characterToPosition = {
  e: ["194-82"],
  t: ["324-82"],
  o: ["140-44"],
  n: ["377-44"],
  u: ["71-60"],
  s: ["446-60"],
  c: ["214-146"],
  d: ["303-146"],
  a: ["317-57"],
  r: ["223-56"],
  h: ["333-121"],
  m: ["207-121"],
  i: ["169-18"],
  l: ["371-19"],
  w: ["224-179"],
  f: ["296-121"],
  g: ["187-180"],
  y: ["439-35"],
  p: ["304-110"],
  b: ["316-180"],
  v: ["215-110"],
  k: ["243-121"],
  j: ["407-18"],
  x: ["323-168"],
  q: ["323-204"],
  z: ["224-180"],
  dup: ["353-179"],
  "'": ["101-35"],
  "past tense": ["40-61"],
  plural: ["500-61"],
  "present tense": ["33-62"],
};
```

**Comment by andy23512** [comment]
I maked all positions in changed lines (exclude format changing lines) with corresponding key for easier to review.

```diff
-    will: ['224-179(w)', '169-18(i)', '371-19(l)'],
+    will: ['224-179(w)', '169-18(i)', '371-19(l)', '353-179(dup)'],
-    your: ['439-35(y)', '223-56(r)'],
+    your: ['439-35(y)', '223-56(r)', '140-44(o)', '71-60(u)'],
-    also: ['317-57(a)', '371-19(l)', '140-44(o)'],
+    also: ['317-57(a)', '371-19(l)', '140-44(o)', '446-60(s)'],
-    as: ['317-57(a)', '446-60(s)'],
+    // as: ['317-57(a)', '446-60(s)'],
-    began: ['316-180(b)', '187-180(g)', '33-62(present tense)'],
+    began: ['316-180(b)', '187-180(g)', '40-61(past tense)'],
-    every: ['194-82(e)', '215-110(v)', '439-35(y)'],
+    every: ['194-82(e)', '215-110(v)', '439-35(y)', '353-179(dup)'],
-    had: ['333-121(h)', '317-57(a)'],
+    had: ['333-121(h)', '317-57(a)', '303-146(d)'],
-    its: ['169-18(i)', '324-82(t)','40-60(present tense)','500-61(plural)'],
+    its: ['169-18(i)', '324-82(t)', '500-61(plural)'],
-    last: ['371-19(l)', '317-57(a)', '324-82(t)'],
+    last: ['371-19(l)', '317-57(a)', '446-60(s)'],
-    near: ['377-44(n)', '223-56(r)'],
+    near: ['377-44(n)', '223-56(r)', '194-82(e)', '317-57(a)'],
-    quick: ['323-204(q)', '71-60(u)', '169-18(i)', '243-121(k)'],
+    quick: ['323-204(q)', '243-121(k)'],
-    quite: ['323-204(q)', '71-60(u)', '324-82(t)', '194-82(e)'],
+    quite: ['323-204(q)', '169-18(i)', '324-82(t)', '194-82(e)'],
-    saw: ['446-60(s)', '224-179(w)'],
+    saw: ['446-60(s)', '317-57(a)'],
-    three: ['324-82(t)', '333-121(h)', '223-56(r)', '194-82(e)'],
+    three: ['324-82(t)', '333-121(h)', '223-56(r)', '194-82(e)', '353-179(dup)'],
-    watch: ['224-179(w)', '324-82(t)', '333-121(h)'],
+    watch: ['224-179(w)', '324-82(t)', '317-57(a)'],
```

**Comment by andy23512** [comment]
For other positions for non character keys, I found them here. https://github.com/iq-eq-us/dot-io/blob/latest_branch/src/data/keyPositions.ts

**Review by COChara — APPROVED** [review]
Thanks Andy23512 for you work on this it looks great! Commit the changed now!

**Pull request merged**
